# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 11"
  - "ios >= 12"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: ""
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "!src/{js,scss,css}/**/*"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "assets/js/core.js"

LOCAL_PATH: "https://plugins.local"
