on:
  pull_request:
    branches-ignore:
      # Do not run on auto submitted branches
      - '**-phpcbf'
    paths:
      - '**.php'

name: PHP Lint

jobs:
  phpcbf-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: cs2pr

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v1"

      - name: PHP Liny
        uses: michaelw90/PHP-Lint@master
